In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


In [2]:
data=pd.read_csv(r"Clustered_mall_customer.csv")


In [10]:
df=pd.DataFrame(data)
x=df.drop(columns=["Cluster"])
x
y=df["Cluster"]
y

0      2
1      2
2      3
3      2
4      2
      ..
195    1
196    4
197    1
198    4
199    1
Name: Cluster, Length: 200, dtype: int64

In [11]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
knn=KNeighborsClassifier()
knn.fit(x_train,y_train)
y_pred=knn.predict(x_test)
score=accuracy_score(y_test,y_pred)
cl_report=classification_report(y_test,y_pred)
confusion_matrix=confusion_matrix(y_test,y_pred)
print("accuracy score:",score)
print("classification report:",cl_report)
print("confusion matrix",confusion_matrix)



accuracy score: 0.975
classification report:               precision    recall  f1-score   support

           0       0.91      1.00      0.95        10
           1       1.00      1.00      1.00         5
           2       1.00      1.00      1.00         3
           3       1.00      0.92      0.96        12
           4       1.00      1.00      1.00        10

    accuracy                           0.97        40
   macro avg       0.98      0.98      0.98        40
weighted avg       0.98      0.97      0.98        40

confusion matrix [[10  0  0  0  0]
 [ 0  5  0  0  0]
 [ 0  0  3  0  0]
 [ 1  0  0 11  0]
 [ 0  0  0  0 10]]


In [12]:
import joblib
joblib.dump(knn,"Kmeans_model.pkl")

['Kmeans_model.pkl']